### ISSUE TITLE
Проверить ДЗ: Топливо с функцией с доктестом в отдельном файле

### ISSUE THREAD

**Issue by Lagunov-PRO** [Lagunov-PRO/HW01_Fuel#1]
@coursar
Добрый день! Прошу принять приглашение и проверить модифицированное ДЗ.

**Comment by coursar** [comment]
Всё ок, но параметр `extra` лучше назвать по-другому. Глядя только на определение функции сложно понять его смысл.

**Comment by Lagunov-PRO** [comment]
@coursar называть аргументы функции так же как  переменные, передаваемые этой функции — нормально ли?

**Comment by coursar** [comment]
Ничего страшного
